# Generated by Django 3.2.9 on 2021-11-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.CharField(max_length=50),
        ),
    ]
